export const GET_DEVICES = "GET_DEVICES";
export const GET_DEVICE = "GET_DEVICE";
export const ADD_DEVICES = "ADD_DEVICE";
export const DELETE_DEVICES = "DELETE_DEVICES";
export const UPDATE_DEVICES = "UPDATE_DEVICES";
export const ERROR_DEVICES = "ERROR_DEVICES";